package com.demo.financial.service;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Tests for FinancialAmountCalculator.
 *
 * <p>The regression test {@code shouldHandleMissingCurrency()} is intentionally
 * left as a placeholder — it will be <b>generated by Claude</b> during the
 * {@code /debug TTP-2847} agentic workflow demo.
 *
 * <p>Run after the fix:
 * <pre>
 *   mvn test -Dtest=FinancialAmountCalculatorTest
 * </pre>
 *
 * @see <a href="https://perinfinity.atlassian.net/browse/TTP-2847">TTP-2847</a>
 */
class FinancialAmountCalculatorTest {

    @Test
    @Disabled("Regression test — generated by /debug TTP-2847 during the agentic demo")
    void shouldHandleMissingCurrency() {
        // Will be implemented by Claude during the demo.
        // Expected: no NPE when portfolio.getCurrency() == null
        // (i.e. legacy FinCore v1 portfolios are handled gracefully)
    }
}
